version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    volumes:
      - .:/var/www
      - ./database/database.sqlite:/var/www/database/database.sqlite
      - ./.env:/var/www/.env
    ports:
      - "8000:8000"
    depends_on:
      - mailhog
    environment:
      - APP_ENV= ${APP_ENV}
      - APP_DEBUG= ${APP_DEBUG}
      - APP_KEY= ${APP_KEY}
    command: >
      sh -c "
        npm run dev &
        php artisan config:clear &&
        php artisan migrate &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"

